### ISSUE TITLE
Explicit public modifier

### ISSUE THREAD

**Issue by aaziz993** [karakum-team/karakum#14]
Hi. Can you please explain me is it possible to add public modifier to externals and variables. I need it because I use explicitApi().

**Comment by turansky** [comment]
Could you solve this problem with linter/formatter?

**Comment by aaziz993** [comment]
> Could you solve this problem with linter/formatter?

Thats the first I thought about, but fow now I have no idea how to configure a rule in linter to add public modifier to all neccessary declaration only in karakum generated directory. Thats why I though mabe karakum has such option and I miss it.

Thanks for reply.
