### ISSUE TITLE
Empty library name in `@file:JsModule`

### ISSUE THREAD

**Issue by shubhamsinghshubham777** [karakum-team/karakum#4]
In the current latest version of this tool, when I'm trying to follow the [Basic Usage](https://github.com/karakum-team/karakum/blob/master/docs/guides/Basic_usage.md) guide, I can observe that the generated file has an empty `JsModule` name:

<img width="1512" alt="Screenshot 2023-05-01 at 5 07 08 PM" src="https://user-images.githubusercontent.com/46640516/235446607-6d74a182-b7bd-4bee-9850-6cb0d4ceb6c2.png">

If I remove the `moduleNameMapper` section from `karakum.config.json`, the JsModule name seems to be generated fine i.e. `@file:JsModule("js-file-download/js-file-download")` ✅

**Comment by sgrishchenko** [comment]
That is right, `moduleNameMapper` behavior was changed but I forgot to update the guide, I will fix it soon.

**Comment by sgrishchenko** [comment]
Also I added [examples](https://github.com/karakum-team/karakum/tree/master/examples/kotlin-js-file-download) with code from [Basic Usage](https://github.com/karakum-team/karakum/blob/master/docs/guides/Basic_usage.md) guide, it seem it works fine now.
